### ISSUE TITLE
Preserve aiming cursor when switching units

### ISSUE THREAD

**Issue by pinobatch** [pinobatch/rhde-nes#4]
When the player switches from a unit operating the silo to a unit carrying a weapon or furniture, the aiming cursor snaps back to the silo. This is exactly the opposite of where the player wants it to be. Save and restore each player's last aiming cursor position.

**Comment by NovaSquirrel** [comment]
I think this would significantly help with the clunkiness involved in having to switch back to non-silo units repeatedly to continue giving them new tasks to do.
