### ISSUE TITLE
Reward duplicate furniture less to discourage toilet spam

### ISSUE THREAD

**Issue by pinobatch** [pinobatch/rhde-nes#5]
The indoor furniture component of a house's score is the sum of these:

- 7 points per item
- 3 points if ficus touches corner or 2 points if it touches wall
- 3 points if rug touches door
- 3 points if bookcase touches wall
- 5 points per item in the same group within 2 cells
- 25 points per each distinct group with all items

The four groups are table and chair; sofa and bookcase; fridge, oven, and trashcan; and toilet, bathtub, and sink.

One of our testers was spamming toilets and sinks to farm their proximity bonus. We should probably cap that to encourage players to incorporate a larger fraction of the necessities of life. Some ideas:

- [ ] Count duplicate furni as not worth the full 7. A duplicate is more than 3 beds, 3 chairs, 2 ficus, 2 rugs, or 1 of most everything else.
- [ ] Award only one proximity bonus per furni type, except chair may earn 2.
- [ ] Cap the ficus, rug, and bookcase placement bonuses as the cap times the maximum value per item.

**Comment by NovaSquirrel** [comment]
Would these checks just be for the player's whole side of the map, ignoring rooms?

**Comment by pinobatch** [comment]
The current check for completing a group of items on a side ignores rooms. I'm pretty sure the proximity check ignores rooms as a programming simplification; I don't know whether it really should.
